### ISSUE TITLE
Add official urls 

### ISSUE THREAD

**Issue by rfd0** [emadmahdi/IPTV#2]
Would you please add the followings to your list
Alanwar1
Alhujja
Alsirat 
Aliman 
Taha 
Hodhod 
Ch14
Alghadeer
Alnajaf 
Almanar 
Alawhad 
Alahad 
Hadi2

Thanks a lot

**Comment by emadmahdi** [comment]
No problem ... i will check these channels ...

**Comment by rfd0** [comment]
Thanks Emad

Also, previously I asked shani if you can do another addon or add to shahid the OSN Play.

**Comment by rfd0** [comment]
Please add https://shiavoice.com thanks

**Comment by emadmahdi** [comment]
Where do you expect me to add it ... I mean which app or which plugin or which addon ?!

**Comment by rfd0** [comment]
Your Kodi Addon. Thanks.

**Comment by emadmahdi** [comment]
Please next time open new github issue using my kodi addon "Arabic Videos" ... This addon you used does not belong to me and stopped long time ago.

Use this link to open new issues for my addon:
https://github.com/emadmahdi/KODI/issues

As for shiavoice website ... does it contain videos or it is only audios ... and also what is the things that exist in shiavoice and does not exist in my program ?!
